<a href="https://colab.research.google.com/github/Bettyrosew/AI-ASSIGNMENT/blob/main/AI_ML_GROUP_TASK_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np


In [10]:
from numpy import array
from keras.activations import sigmoid
from keras.losses import mse
from sklearn.preprocessing import Normalizer
from numpy.random import uniform

In [12]:
batch_size=1

In [14]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}
dataset=pd.DataFrame(data)

**Dataset**

In [15]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [18]:
x=dataset.drop('Target',axis=1)
y=dataset['Target']
x

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [22]:
norm_x = Normalizer(norm='max').fit_transform(x)
norm_x

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [23]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [25]:
norm_y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))
norm_y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

**ANN**

In [26]:
weight1=uniform(-1,1,(3,2)) #shape 3 by 2
weight2=uniform(-1,1,(2,1))
weight1

array([[0.78685595, 0.76703778],
       [0.2281617 , 0.13597622],
       [0.40508516, 0.50285226]])

In [27]:
weight2

array([[0.6147076 ],
       [0.86376637]])

In [31]:
for i in range(100):
  norm_x[0:batch_size]
  output1=norm_x[0:batch_size]@weight1
  actual_output=sigmoid(output1).numpy()
  predicted_output=actual_output@weight2
  predicted_output=np.reshape(predicted_output,(1,-1))

In [32]:
output1

array([[1.05972809, 1.07185591]])

In [33]:
actual_output

array([[0.74263858, 0.7449497 ]])

In [35]:
predicted_output

array([[1.09996808]])